name: Faceless automation

on:
  # schedule:
  #   # Run the workflow every 6 hours
  #   - cron: '0 */6 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # You can specify the Python version you need

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      # Install dependencies (if you have a requirements.txt)
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Run the Python script
      - name: Run Python script
        run: |
          python main.py
